'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api, errorMessage } from '@/lib/api';
import { Icon } from '@/components/Icon';

type Site = { id: string; name: string; url: string };
type Summary = { today: { visitors: number; conversations: number; popupDisplayed: number; popupClicked: number; chatOpens: number; popupCtr: number }; topPages: Array<{ pagePath: string; pageTitle: string | null; conversations: number; events: number }> };
type Lead = { id: string; name: string | null; email: string | null; scorePercent: number; scoreLabel: string; status: string; capturedAt: string; website: Site; conversation: { id: string; title: string } };
type Conversation = { id: string; visitorId: string | null; title: string; status: string; summary: string | null; totalMessages: number; messageCount?: number; currentPage: string | null; device: string | null; startedAt: string; lastMessageAt: string };
type ConversationDetail = Conversation & { messages: Array<{ id: string; role: 'user' | 'assistant'; content: string; timestamp: string; source: { title: string; url: string } | null }>; memories: Array<{ id: string; kind: string; content: string; confidence: number | null }> };
type Decision = { id: string; occurredAt: string; websiteId: string; website: Site; sessionId: string; visitorId: string | null; pageUrl: string | null; pagePath: string | null; pageTitle: string | null; behaviorSummary: string | null; intentSummary: string | null; intentGoal: string | null; confidenceScore: number | null; confidenceBand: string | null; decision: string; reason: string | null; popupGenerated: boolean; popupSuppressed: boolean; suppressionReason: string | null; generatedPopupTitle: string | null; ctaText: string | null; expectedAction: boolean; primaryActionReturned: string | null; llmUsed: boolean; validationPassed: boolean; finalOutcome: string; popupDisplayed: boolean; popupClicked: boolean; popupDismissed: boolean; chatOpened: boolean };

const SITE_KEY = 'dashboard:selectedWebsiteId';
const emptySummary: Summary = { today: { visitors: 0, conversations: 0, popupDisplayed: 0, popupClicked: 0, chatOpens: 0, popupCtr: 0 }, topPages: [] };

function relativeTime(value?: string | null) {
  if (!value) return 'Not available';
  const minutes = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 60000));
  if (!Number.isFinite(minutes)) return 'Not available';
  if (minutes < 1) return 'Just now';
  if (minutes < 60) return `${minutes}m ago`;
  if (minutes < 1440) return `${Math.round(minutes / 60)}h ago`;
  return `${Math.round(minutes / 1440)}d ago`;
}

function label(value?: string | null) {
  return (value || 'Not available').replace(/_/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());
}

function confidence(value: number | null) { return value == null ? 'Not scored' : `${Math.round(value * 100)}%`; }

export function PageHeader({ title, description, action, children }: { title: string; description: string; action?: React.ReactNode; children?: React.ReactNode }) {
  return <header className="ops-page-header"><div><p className="ops-eyebrow">Revenue operations</p><h1>{title}</h1><p>{description}</p></div><div className="ops-header-actions">{children}{action}</div></header>;
}

export function SiteSwitcher({ sites, value, onChange, allowAll = false }: { sites: Site[]; value: string; onChange: (value: string) => void; allowAll?: boolean }) {
  return <label className="ops-site-switcher"><span>Site</span><select value={value} onChange={(event) => onChange(event.target.value)} aria-label="Select site">{allowAll && <option value="">All sites</option>}{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label>;
}

export function StatusIndicator({ tone = 'neutral', children }: { tone?: 'live' | 'attention' | 'neutral'; children: React.ReactNode }) {
  return <span className={`ops-status ops-status--${tone}`}><span aria-hidden="true" />{children}</span>;
}

export function LoadingSkeleton({ lines = 3 }: { lines?: number }) { return <div className="ops-skeleton" aria-label="Loading">{Array.from({ length: lines }, (_, index) => <span key={index} style={{ width: `${92 - index * 18}%` }} />)}</div>; }

export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <section className="ops-empty"><span className="ops-empty-mark" aria-hidden="true">—</span><h2>{title}</h2><p>{description}</p>{action && <div>{action}</div>}</section>; }

export function ErrorState({ title = 'Unable to load this view', error, onRetry }: { title?: string; error: string; onRetry?: () => void }) { return <section className="ops-error" role="alert"><div><strong>{title}</strong><p>{error}</p></div>{onRetry && <button className="ops-button ops-button--secondary" onClick={onRetry}>Try again</button>}</section>; }

export function MetricGroup({ items }: { items: Array<{ label: string; value: string | number; detail?: string }> }) { return <div className="ops-metric-group">{items.map((item) => <div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd>{item.detail && <p>{item.detail}</p>}</div>)}</div>; }

type ThreadStep = { stage: string; value: string; detail?: string; tone?: 'intent' | 'neutral' | 'success' };
export function IntentTrace({ steps, compact = false }: { steps: ThreadStep[]; compact?: boolean }) { return <ol className={`ops-intent-trace ${compact ? 'ops-intent-trace--compact' : ''}`}>{steps.map((step) => <li key={step.stage} className={step.tone ? `is-${step.tone}` : ''}><span className="ops-thread-dot" aria-hidden="true" /><div><span>{step.stage}</span><strong>{step.value}</strong>{step.detail && <p>{step.detail}</p>}</div></li>)}</ol>; }

function getDecisionSteps(item: Decision): ThreadStep[] {
  const observed = item.behaviorSummary || item.pageTitle || item.pagePath || 'Visitor behavior observed';
  const inferred = item.intentSummary || item.intentGoal ? `${item.intentSummary || label(item.intentGoal)} · ${confidence(item.confidenceScore)}` : `Decision: ${label(item.decision)}`;
  const acted = item.popupDisplayed || item.popupGenerated ? item.generatedPopupTitle || item.ctaText || 'Proactive prompt prepared' : item.popupSuppressed ? `No popup shown${item.suppressionReason ? ` — ${item.suppressionReason}` : ''}` : 'No proactive action recorded';
  const outcome = item.chatOpened ? 'Conversation opened' : item.popupClicked ? 'Popup clicked' : item.popupDismissed ? 'Popup dismissed' : label(item.finalOutcome);
  return [{ stage: 'Observed', value: observed }, { stage: 'Interpreted', value: inferred, tone: 'intent' }, { stage: 'Acted', value: acted }, { stage: 'Outcome', value: outcome, tone: item.chatOpened || item.popupClicked ? 'success' : 'neutral' }];
}

function useSiteScope() {
  const [sites, setSites] = useState<Site[]>([]); const [siteId, setSiteId] = useState(''); const [siteError, setSiteError] = useState('');
  const loadSites = useCallback(() => api.listWebsites().then((data) => { const next = data as Site[]; setSites(next); const stored = window.localStorage.getItem(SITE_KEY); setSiteId((current) => current || next.find((site) => site.id === stored)?.id || next[0]?.id || ''); }).catch((error) => setSiteError(errorMessage(error, 'Unable to load sites.'))), []);
  useEffect(() => { void loadSites(); }, [loadSites]);
  const setSelectedSite = (value: string) => { setSiteId(value); if (value) window.localStorage.setItem(SITE_KEY, value); };
  return { sites, siteId, setSelectedSite, siteError, loadSites };
}

export function OverviewView() {
  const { sites, siteId, setSelectedSite, siteError, loadSites } = useSiteScope();
  const [summary, setSummary] = useState<Summary>(emptySummary); const [leads, setLeads] = useState<Lead[]>([]); const [decisions, setDecisions] = useState<Decision[]>([]); const [knowledge, setKnowledge] = useState<{ hasKnowledge?: boolean; lastBuild?: { createdAt?: string; status?: string } } | null>(null); const [widget, setWidget] = useState<{ status?: string } | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!siteId) return; setLoading(true); setError(''); try { const [summaryData, leadData, decisionData, knowledgeData, widgetData] = await Promise.all([api.getAnalyticsSummary(siteId), api.listLeads(siteId), api.getAiDecisionLog({ websiteId: siteId, limit: 12 }), api.getKnowledgeStatus(siteId), api.getWidget(siteId)]); setSummary(summaryData as Summary); setLeads(leadData as Lead[]); setDecisions((decisionData as { logs: Decision[] }).logs ?? []); setKnowledge(knowledgeData as typeof knowledge); setWidget(widgetData as typeof widget); } catch (cause) { setError(errorMessage(cause, 'Unable to load overview.')); } finally { setLoading(false); } }, [siteId]);
  useEffect(() => { void load(); }, [load]);
  const latest = decisions[0]; const selectedSite = sites.find((site) => site.id === siteId);
  if (siteError) return <ErrorState error={siteError} onRetry={() => void loadSites()} />;
  return <div className="ops-page"> <PageHeader title="Overview" description="See what your AI employee is noticing, doing, and creating for this site." action={<Link href="/activity" className="ops-button">View activity</Link>}><SiteSwitcher sites={sites} value={siteId} onChange={setSelectedSite} /></PageHeader>{!siteId && !loading ? <EmptyState title="Connect a site to begin" description="Your AI employee needs a public site before it can learn, engage visitors, and surface revenue activity." action={<Link className="ops-button" href="/onboarding">Start launch</Link>} /> : error ? <ErrorState error={error} onRetry={() => void load()} /> : loading ? <OverviewLoading /> : <>
    <section className="ops-health" aria-label="AI employee status"><div><p className="ops-eyebrow">AI employee</p><h2>{selectedSite?.name || 'Selected site'}</h2><StatusIndicator tone={widget?.status === 'ACTIVE' && knowledge?.hasKnowledge ? 'live' : 'attention'}>{widget?.status === 'ACTIVE' && knowledge?.hasKnowledge ? 'Live and ready' : 'Needs attention'}</StatusIndicator></div><dl><div><dt>Knowledge</dt><dd>{knowledge?.hasKnowledge ? 'Ready' : 'Not built'}</dd><p>{knowledge?.lastBuild?.createdAt ? `Updated ${relativeTime(knowledge.lastBuild.createdAt)}` : 'Build knowledge to answer visitors.'}</p></div><div><dt>Widget</dt><dd>{widget?.status === 'ACTIVE' ? 'Installed' : 'Not verified'}</dd><p>{widget?.status === 'ACTIVE' ? 'Receiving visitor activity.' : 'Finish installation to engage visitors.'}</p></div></dl></section>
    <section className="ops-region"><div className="ops-region-heading"><div><p className="ops-eyebrow">Intent thread</p><h2>Latest meaningful activity</h2><p>The evidence behind the most recent AI decision.</p></div>{latest && <Link href="/activity" className="ops-text-link">Open activity <Icon name="arrow_right" /></Link>}</div>{latest ? <div className="ops-thread-feature"><div><span className="ops-time">{relativeTime(latest.occurredAt)}</span><h3>{latest.pageTitle || latest.pagePath || 'Visitor session'}</h3><p>{latest.reason || 'A recent visitor event was evaluated by your AI employee.'}</p></div><IntentTrace steps={getDecisionSteps(latest)} /></div> : <EmptyState title="No intent activity yet" description="Once the widget sees visitor behavior, the decision trail will appear here. You can finish launch and verify the widget in the meantime." action={<Link href="/onboarding" className="ops-button ops-button--secondary">Check launch status</Link>} />}</section>
    <section className="ops-region"><div className="ops-region-heading"><div><p className="ops-eyebrow">Today</p><h2>Revenue signal</h2></div></div><MetricGroup items={[{ label: 'Qualified leads', value: leads.length, detail: leads.length ? 'Captured from visitor conversations' : 'No leads captured yet' }, { label: 'Proactive conversations', value: summary.today.chatOpens, detail: `${summary.today.popupDisplayed} prompts shown` }, { label: 'Engagement rate', value: summary.today.popupDisplayed ? `${Math.round((summary.today.popupClicked / summary.today.popupDisplayed) * 100)}%` : '—', detail: 'Prompt clicks / prompts shown' }, { label: 'Visitors observed', value: summary.today.visitors, detail: 'Today' }]} /></section>
    <section className="ops-overview-grid"><div className="ops-region"><div className="ops-region-heading"><div><p className="ops-eyebrow">Recent</p><h2>High-intent activity</h2></div><Link href="/activity" className="ops-text-link">All activity <Icon name="arrow_right" /></Link></div><div className="ops-activity-preview">{decisions.slice(0, 4).map((decision) => <Link key={decision.id} href={`/activity?decision=${decision.id}`} className="ops-preview-row"><span>{relativeTime(decision.occurredAt)}</span><div><strong>{decision.intentSummary || label(decision.decision)}</strong><p>{decision.behaviorSummary || decision.pagePath || 'Visitor activity evaluated'}</p></div><StatusIndicator tone={decision.chatOpened || decision.popupClicked ? 'live' : decision.confidenceScore && decision.confidenceScore >= .7 ? 'attention' : 'neutral'}>{decision.chatOpened ? 'Engaged' : confidence(decision.confidenceScore)}</StatusIndicator></Link>)}{decisions.length === 0 && <p className="ops-muted">No decisions recorded yet.</p>}</div></div><div className="ops-region"><div className="ops-region-heading"><div><p className="ops-eyebrow">Attention</p><h2>Operational health</h2></div></div><ul className="ops-health-list"><li><span>{knowledge?.hasKnowledge ? 'Knowledge is ready' : 'Knowledge needs a build'}</span><small>{knowledge?.hasKnowledge ? 'Your AI can use site knowledge.' : 'Build knowledge before going live.'}</small></li><li><span>{widget?.status === 'ACTIVE' ? 'Widget is active' : 'Widget installation needs verification'}</span><small>{widget?.status === 'ACTIVE' ? 'Visitor events can be recorded.' : 'Verify the installation on your site.'}</small></li><li><span>{leads.length ? `${leads.length} qualified lead${leads.length === 1 ? '' : 's'} ready to review` : 'No leads waiting'}</span><small>{leads.length ? 'Open Leads to take the next step.' : 'New leads will appear after conversations qualify.'}</small></li></ul></div></section>
  </>}</div>;
}

function OverviewLoading() { return <div className="ops-page"><LoadingSkeleton lines={2} /><div className="ops-loading-block"><LoadingSkeleton lines={5} /></div><div className="ops-loading-block"><LoadingSkeleton lines={4} /></div></div>; }

type ActivityItem = { id: string; kind: 'decision' | 'conversation'; occurredAt: string; title: string; subtitle: string; decision?: Decision; conversation?: Conversation };
export function ActivityView() {
  const { sites, siteId, setSelectedSite, siteError, loadSites } = useSiteScope(); const [decisions, setDecisions] = useState<Decision[]>([]); const [conversations, setConversations] = useState<Conversation[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [intentFilter, setIntentFilter] = useState('all'); const [outcomeFilter, setOutcomeFilter] = useState('all'); const [selectedId, setSelectedId] = useState('');
  const load = useCallback(async () => { if (!siteId) return; setLoading(true); setError(''); try { const [decisionData, conversationData] = await Promise.all([api.getAiDecisionLog({ websiteId: siteId, limit: 100 }), api.listConversations(siteId)]); setDecisions((decisionData as { logs: Decision[] }).logs ?? []); setConversations(conversationData as Conversation[]); } catch (cause) { setError(errorMessage(cause, 'Unable to load activity.')); } finally { setLoading(false); } }, [siteId]);
  useEffect(() => { void load(); }, [load]);
  const items = useMemo(() => { const list: ActivityItem[] = [...decisions.map((decision) => ({ id: `decision-${decision.id}`, kind: 'decision' as const, occurredAt: decision.occurredAt, title: decision.intentSummary || label(decision.decision), subtitle: decision.behaviorSummary || decision.pagePath || 'Visitor behavior evaluated', decision })), ...conversations.map((conversation) => ({ id: `conversation-${conversation.id}`, kind: 'conversation' as const, occurredAt: conversation.lastMessageAt || conversation.startedAt, title: conversation.title || 'Visitor conversation', subtitle: conversation.summary || conversation.currentPage || 'Conversation activity', conversation }))]; return list.filter((item) => { const decision = item.decision; const matchesIntent = intentFilter === 'all' || (decision?.intentGoal || decision?.decision || '').toLowerCase().includes(intentFilter); const matchesOutcome = outcomeFilter === 'all' || (outcomeFilter === 'engaged' && (decision?.chatOpened || item.kind === 'conversation')) || (outcomeFilter === 'lead' && decision?.finalOutcome.toLowerCase().includes('lead')); return matchesIntent && matchesOutcome; }).sort((a, b) => +new Date(b.occurredAt) - +new Date(a.occurredAt)); }, [conversations, decisions, intentFilter, outcomeFilter]);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get('decision'); const candidate = requested ? `decision-${requested}` : items[0]?.id; setSelectedId((current) => current || candidate || ''); }, [items]);
  const selected = items.find((item) => item.id === selectedId);
  if (siteError) return <ErrorState error={siteError} onRetry={() => void loadSites()} />;
  return <div className="ops-page"><PageHeader title="Activity" description="A live operational record of what visitors did, what your AI inferred, and what happened next."><SiteSwitcher sites={sites} value={siteId} onChange={setSelectedSite} /></PageHeader>{!siteId && !loading ? <EmptyState title="No site selected" description="Connect a site to see its visitor and AI activity." action={<Link className="ops-button" href="/onboarding">Start launch</Link>} /> : error ? <ErrorState error={error} onRetry={() => void load()} /> : <><div className="ops-filter-bar"><label>Intent<select value={intentFilter} onChange={(event) => setIntentFilter(event.target.value)}><option value="all">All intent</option><option value="purchase">Purchase</option><option value="pricing">Pricing</option><option value="demo">Demo</option></select></label><label>Outcome<select value={outcomeFilter} onChange={(event) => setOutcomeFilter(event.target.value)}><option value="all">All outcomes</option><option value="engaged">Engaged</option><option value="lead">Lead captured</option></select></label><button className="ops-button ops-button--quiet" onClick={() => void load()}><Icon name="refresh" /> Refresh</button></div>{loading ? <ActivityLoading /> : items.length === 0 ? <EmptyState title="No activity yet" description="Activity will appear when the widget records visitor behavior or conversations. This feed uses real events only." action={<Link href="/onboarding" className="ops-button ops-button--secondary">Verify widget</Link>} /> : <div className={`ops-activity-layout ${selected ? 'has-selection' : ''}`}><section className="ops-activity-list" aria-label="Activity sessions">{items.map((item) => <ActivityRow key={item.id} item={item} selected={selectedId === item.id} onSelect={() => setSelectedId(item.id)} />)}</section><DetailPanel item={selected} onClose={() => setSelectedId('')} /></div>}</>}</div>;
}

function ActivityLoading() { return <div className="ops-activity-layout"><div className="ops-activity-list"><LoadingSkeleton lines={8} /></div><div className="ops-detail-panel"><LoadingSkeleton lines={8} /></div></div>; }

function ActivityRow({ item, selected, onSelect }: { item: ActivityItem; selected: boolean; onSelect: () => void }) { const trace = item.decision ? getDecisionSteps(item.decision) : [{ stage: 'Observed', value: item.subtitle }, { stage: 'Outcome', value: `${item.conversation?.messageCount ?? item.conversation?.totalMessages ?? 0} messages`, tone: 'success' as const }]; return <button className={`ops-activity-row ${selected ? 'is-selected' : ''}`} onClick={onSelect}><time>{relativeTime(item.occurredAt)}</time><div className="ops-activity-row-main"><div className="ops-activity-row-title"><strong>{item.title}</strong><StatusIndicator tone={item.decision?.chatOpened || item.kind === 'conversation' ? 'live' : item.decision?.confidenceScore && item.decision.confidenceScore >= .7 ? 'attention' : 'neutral'}>{item.kind === 'conversation' ? 'Conversation' : item.decision?.chatOpened ? 'Engaged' : confidence(item.decision?.confidenceScore ?? null)}</StatusIndicator></div><p>{item.subtitle}</p><IntentTrace steps={trace} compact /></div><Icon name="arrow_right" /></button>; }

function DetailPanel({ item, onClose }: { item?: ActivityItem; onClose: () => void }) { const [detail, setDetail] = useState<ConversationDetail | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); useEffect(() => { if (!item?.conversation) { setDetail(null); setError(''); return; } let alive = true; setLoading(true); setError(''); api.getConversation(item.conversation.id).then((data) => alive && setDetail(data as ConversationDetail)).catch((cause) => alive && setError(errorMessage(cause, 'Unable to load conversation detail.'))).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [item?.conversation?.id]); if (!item) return <aside className="ops-detail-panel ops-detail-panel--empty"><EmptyState title="Select an activity" description="Choose a decision or conversation to inspect the evidence and outcome." /></aside>; const decision = item.decision; return <aside className="ops-detail-panel" aria-label="Activity detail"><div className="ops-detail-top"><div><span className="ops-eyebrow">{item.kind === 'decision' ? 'AI decision' : 'Visitor session'}</span><h2>{item.title}</h2><p>{relativeTime(item.occurredAt)}</p></div><button className="ops-icon-button" aria-label="Close detail" onClick={onClose}><Icon name="close" /></button></div>{decision ? <><section className="ops-detail-section"><h3>Intent thread</h3><IntentTrace steps={getDecisionSteps(decision)} /></section><section className="ops-detail-section"><h3>Why we acted</h3><p>{decision.reason || 'No additional explanation was recorded for this decision.'}</p></section><section className="ops-detail-section"><h3>What we said</h3><div className="ops-said">{decision.generatedPopupTitle || decision.ctaText || (decision.popupSuppressed ? 'The AI did not show a popup for this event.' : 'No visitor-facing message was recorded.')}</div></section><details className="ops-advanced"><summary>Advanced decision details</summary><dl><div><dt>Confidence</dt><dd>{confidence(decision.confidenceScore)} {decision.confidenceBand ? `· ${label(decision.confidenceBand)}` : ''}</dd></div><div><dt>Validation</dt><dd>{decision.validationPassed ? 'Passed' : 'Not passed / unavailable'}</dd></div><div><dt>Model path</dt><dd>{decision.llmUsed ? 'Model-assisted' : 'Rules / fallback'}</dd></div><div><dt>Session ID</dt><dd className="ops-mono">{decision.sessionId}</dd></div></dl></details></> : loading ? <LoadingSkeleton lines={8} /> : error ? <ErrorState title="Conversation unavailable" error={error} /> : detail ? <ConversationDetailView detail={detail} /> : null}</aside>; }

function ConversationDetailView({ detail }: { detail: ConversationDetail }) { return <><section className="ops-detail-section"><h3>Session summary</h3><p>{detail.summary || 'No AI summary is available yet for this conversation.'}</p><dl className="ops-summary-grid"><div><dt>Page</dt><dd>{detail.currentPage || 'Not recorded'}</dd></div><div><dt>Device</dt><dd>{detail.device || 'Not recorded'}</dd></div><div><dt>Messages</dt><dd>{detail.messageCount ?? detail.totalMessages}</dd></div><div><dt>Visitor</dt><dd className="ops-mono">{detail.visitorId?.slice(0, 12) || 'Anonymous'}</dd></div></dl></section><section className="ops-detail-section"><h3>What the visitor did</h3><div className="ops-message-list">{detail.messages.map((message) => <div key={message.id} className={`ops-message ops-message--${message.role}`}><span>{message.role === 'user' ? 'Visitor' : 'AI employee'}</span><p>{message.content}</p>{message.source && <small>Source: {message.source.title}</small>}</div>)}</div></section>{detail.memories.length > 0 && <details className="ops-advanced"><summary>Session memory</summary>{detail.memories.map((memory) => <p key={memory.id}><strong>{label(memory.kind)}:</strong> {memory.content}</p>)}</details>}</>; }
